runtime: nodejs10
service: nextjs

handlers:
  - url: /(.*\.(gif|png|jpg|ico|svg|txt))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|ico|svg|txt)$

  - url: /_next/static
    static_dir: .next/static

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
